name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pandas=2.3.3
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - pytorch=2.9.0
  - torchvision
  - torchaudio
  - tqdm=4.67.1
  - pip:
      - acres==0.5.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asgiref==3.10.0
      - attrs==25.4.0
      - av==16.0.1
      - backoff==2.2.1
      - bcrypt==5.0.0
      - blinker==1.9.0
      - build==1.3.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - chromadb==0.5.23
      - click==8.3.0
      - clickhouse-connect==0.6.6
      - coloredlogs==15.0.1
      - configobj==5.0.9
      - cryptography==46.0.3
      - ctranslate2==4.6.0
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - dnspython==2.8.0
      - duckdb==0.7.1
      - durationpy==0.10
      - edge-tts==7.2.3
      - fastapi==0.119.0
      - faster-whisper==1.2.0
      - filelock==3.20.0
      - Flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - fsspec==2025.9.0
      - google-auth==2.41.1
      - grpcio==1.76.0
      - h11==0.16.0
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - Jinja2==3.1.6
      - joblib==1.5.2
      - kubernetes==34.1.0
      - langchain==0.1.14
      - langchain-chroma==0.1.4
      - langchain-community==0.0.38
      - langchain-core==0.1.53
      - langchain-huggingface==0.0.3
      - langchain-openai==0.1.1
      - langchain-text-splitters==0.0.2
      - langsmith==0.1.147
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.2.0
      - networkx==3.5
      - nibabel==5.3.2
      - nipype==1.10.0
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - openai==1.109.1
      - opentelemetry-api==1.38.0
      - opentelemetry-sdk==1.38.0
      - orjson==3.11.4
      - packaging==23.2
      - pathlib==1.0.1
      - pdfminer.six==20250506
      - pdfplumber==0.11.7
      - pillow==12.0.0
      - posthog==6.7.10
      - propcache==0.4.1
      - protobuf==6.33.0
      - puremagic==1.30
      - PyPDF2==3.0.1
      - pypdfium2==5.0.0
      - python-dotenv==1.1.1
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - sentence-transformers==5.1.2
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tiktoken==0.11.0
      - tokenizers==0.20.3
      - transformers==4.46.3
      - typer==0.20.0
      - typing_extensions==4.15.0
      - tzdata==2025.2
      - uvicorn==0.38.0
      - websocket-client==1.9.0
      - websockets==15.0.1
      - Werkzeug==3.1.3
      - zstandard==0.25.0
